version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
      - '8001:8001'

volumes:
  redis-data:
